server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://hyun-db.ccauqzjy5dsv.ap-northeast-2.rds.amazonaws.com/Delivery?autoReconnect=true
    username: admin
    password: dkrkto29!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

